export const QUESTION_TEXT_PHRASE_CORRECTIONS = [
  ['top left sid if each display', 'top left side of each display'],
  ['top left side if each display', 'top left side of each display'],
  ['Lock th e mask', 'Lock the mask'],
  ['aft bottom ri g ht side', 'aft bottom right side'],
  ['oxygen pressure d isplayed', 'oxygen pressure displayed'],
  ['oxygen shutof f valve', 'oxygen shutoff valve'],
  ['answer s are correct', 'answers are correct'],
  ['condition s exist', 'conditions exist'],
]

export const QUESTION_TEXT_SPLIT_WORD_DICTIONARY = [
  'the',
  'there',
  'their',
  'when',
  'where',
  'which',
  'what',
  'side',
  'right',
  'left',
  'bottom',
  'top',
  'displayed',
  'display',
  'displays',
  'condition',
  'conditions',
  'answer',
  'answers',
  'system',
  'systems',
  'switch',
  'switches',
  'valve',
  'valves',
  'source',
  'sources',
  'external',
  'located',
  'service',
  'serving',
  'pressure',
  'indicator',
  'momentary',
  'momentarily',
  'oxygen',
  'mask',
  'masks',
  'release',
  'lever',
  'stowage',
  'microphone',
  'flight',
  'deck',
  'fuselage',
  'cylinder',
  'shutoff',
  'anti-ice',
  'anti ice',
  'cowling',
  'cowl',
  'engine',
  'engines',
  'hydraulic',
  'hydraulics',
  'electrical',
  'generator',
  'generators',
  'autopilot',
  'autothrottle',
  'unit',
  'EICAS',
  'APU',
  'ENG',
  'TAI',
  'UDU',
  'PFD',
  'ND',
  'MEL',
  'QRH',
  'FCOM',
]
